
import Head from 'next/head'
import styles from '@/styles/forgotpass.module.css'
import Link from 'next/link'

function NewPass() {
  return (
    <>
      <Head>
        <title>Forgot Password</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.contentbody}>
            <div className= {styles.top} >
            Reset Your Password
            </div>
            <div className= {styles.low} >
                <form className= {styles.FormDetails}>
                    <div className={styles.FPDetails}>
                        <div className={styles.FPLabels}>
                        New Password:
                        </div>
                        <input type="password" className={styles.FPInputs} required/>
                    </div>
                    <div className={styles.FPDetails}>
                        <div className={styles.FPLabels}>
                        Confirm Password:
                        </div>
                        <input type="password" className={styles.FPInputs} required/>
                    </div>
                    <input type='submit' value= 'Sign Up' className={styles.submitbttn}/>
                </form>
            </div>
        </div>
      </main>
    </>
  )
}
export default NewPass